<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType></PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia.Headless" Version="12.1.1" />
    <ProjectReference Include="../../src/LLamaModelLoader.Desktop/LLamaModelLoader.Desktop.csproj" />
  </ItemGroup>
</Project>
